# Generated by Django 5.0 on 2024-08-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
